import 'package:http/http.dart' as http;
import 'package:html/parser.dart' show parse;
import 'package:html/dom.dart';
import 'dart:convert';

final res = '''
[
    {
        "fest_id": 999605,
        "fest_tipo": "N",
        "fest_tipo_descr": "Normal",
        "cur_nome": "Mestrado Integrado em Engenharia Informática e Computação",
        "cur_name": "Master in Informatics and Computing Engineering",
        "cur_sigla": "MIEIC",
        "ano_curricular": "3",
        "media": 16.9,
        "inscricoes": [
            {
                "ucurr_id": 224676,
                "ucurr_codigo": "EIC0004",
                "ucurr_sigla": "AMAT",
                "ucurr_nome": "Análise Matemática",
                "ucurr_name": "Mathematical Analysis",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384922,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304180,
                "inst_id": 1298404,
                "comp_id": 280089,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "16",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226117,
                "ucurr_codigo": "EIC0083",
                "ucurr_sigla": "AOCO",
                "ucurr_nome": "Arquitectura e Organização de Computadores",
                "ucurr_name": "Computer Architecture and Organization",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384925,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304178,
                "inst_id": 1298402,
                "comp_id": 280087,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "15",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224677,
                "ucurr_codigo": "EIC0005",
                "ucurr_sigla": "FPRO",
                "ucurr_nome": "Fundamentos da Programação",
                "ucurr_name": "Programming Fundamentals",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384923,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304179,
                "inst_id": 1298403,
                "comp_id": 280088,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "19",
                "resultado_ects": "A",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224683,
                "ucurr_codigo": "EIC0011",
                "ucurr_sigla": "MDIS",
                "ucurr_nome": "Matemática Discreta",
                "ucurr_name": "Discrete Mathematics",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384924,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304177,
                "inst_id": 1298401,
                "comp_id": 280086,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "16",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224904,
                "ucurr_codigo": "FEUP002",
                "ucurr_sigla": "PF",
                "ucurr_nome": "Projeto FEUP",
                "ucurr_name": "Project FEUP",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 387801,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304182,
                "inst_id": 1304269,
                "comp_id": 284527,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "17",
                "resultado_ects": "A",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 1.5,
                "creditos_ects": 1.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224675,
                "ucurr_codigo": "EIC0003",
                "ucurr_sigla": "ALGE",
                "ucurr_nome": "Álgebra",
                "ucurr_name": "Algebra",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384921,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304181,
                "inst_id": 1298405,
                "comp_id": 280090,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "17",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 4.5,
                "creditos_ects": 4.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224681,
                "ucurr_codigo": "EIC0009",
                "ucurr_sigla": "CMAT",
                "ucurr_nome": "Complementos de Matemática",
                "ucurr_name": "Complements of Mathematics",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384926,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304277,
                "inst_id": 1298399,
                "comp_id": 280084,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "O",
                "avaliacao": "",
                "resultado_melhor": "16",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224682,
                "ucurr_codigo": "EIC0010",
                "ucurr_sigla": "FISI1",
                "ucurr_nome": "Física I",
                "ucurr_name": "Physics I",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384927,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304276,
                "inst_id": 1298398,
                "comp_id": 280083,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "16",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224688,
                "ucurr_codigo": "EIC0016",
                "ucurr_sigla": "MPCP",
                "ucurr_nome": "Microprocessadores e Computadores Pessoais",
                "ucurr_name": "Microprocessors and Personal Computers",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384929,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304278,
                "inst_id": 1298411,
                "comp_id": 280096,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "16",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226136,
                "ucurr_codigo": "EIC0105",
                "ucurr_sigla": "MEST",
                "ucurr_nome": "Métodos Estatísticos",
                "ucurr_name": "Statistical Methods",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384930,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304274,
                "inst_id": 1298376,
                "comp_id": 280061,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "14",
                "resultado_ects": "B",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 4.5,
                "creditos_ects": 4.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224684,
                "ucurr_codigo": "EIC0012",
                "ucurr_sigla": "PROG",
                "ucurr_nome": "Programação",
                "ucurr_name": "Programming",
                "a_lectivo": 2016,
                "ano": 1,
                "ocorr_id": 384928,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11304275,
                "inst_id": 1298397,
                "comp_id": 280082,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "O",
                "avaliacao": "",
                "resultado_melhor": "19",
                "resultado_ects": "A",
                "aval_a_lectivo": 2016,
                "resultado_insc": "A",
                "creditos_ucn": 7.5,
                "creditos_ects": 7.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224685,
                "ucurr_codigo": "EIC0013",
                "ucurr_sigla": "AEDA",
                "ucurr_nome": "Algoritmos e Estruturas de Dados",
                "ucurr_name": "Algorithms and Data Structures",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399886,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521910,
                "inst_id": 1298396,
                "comp_id": 280081,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "19",
                "resultado_ects": "A",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 7.5,
                "creditos_ects": 7.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224686,
                "ucurr_codigo": "EIC0014",
                "ucurr_sigla": "FISI2",
                "ucurr_nome": "Física II",
                "ucurr_name": "Physics II",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399887,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521909,
                "inst_id": 1298395,
                "comp_id": 280080,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "18",
                "resultado_ects": "B",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224692,
                "ucurr_codigo": "EIC0020",
                "ucurr_sigla": "LCOM",
                "ucurr_nome": "Laboratório de Computadores",
                "ucurr_name": "Computer Laboratory",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399888,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521911,
                "inst_id": 1298410,
                "comp_id": 280095,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "19",
                "resultado_ects": "A",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224693,
                "ucurr_codigo": "EIC0021",
                "ucurr_sigla": "MNUM",
                "ucurr_nome": "Métodos Numéricos",
                "ucurr_name": "Numerical Methods",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399889,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521908,
                "inst_id": 1298394,
                "comp_id": 280079,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "20",
                "resultado_ects": "A",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 4.5,
                "creditos_ects": 4.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224694,
                "ucurr_codigo": "EIC0022",
                "ucurr_sigla": "TCOM",
                "ucurr_nome": "Teoria da Computação",
                "ucurr_name": "Computing Theory",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399890,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521907,
                "inst_id": 1298393,
                "comp_id": 280078,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "12",
                "resultado_ects": "C",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224695,
                "ucurr_codigo": "EIC0023",
                "ucurr_sigla": "BDAD",
                "ucurr_nome": "Bases de Dados",
                "ucurr_name": "Databases",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399892,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521912,
                "inst_id": 1298374,
                "comp_id": 280059,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "17",
                "resultado_ects": "A",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224691,
                "ucurr_codigo": "EIC0019",
                "ucurr_sigla": "CGRA",
                "ucurr_nome": "Computação Gráfica",
                "ucurr_name": "Computer Graphics",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399891,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521914,
                "inst_id": 1298392,
                "comp_id": 280077,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "17",
                "resultado_ects": "B",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226163,
                "ucurr_codigo": "EIC0110",
                "ucurr_sigla": "CAL",
                "ucurr_nome": "Concepção e Análise de Algoritmos",
                "ucurr_name": "Algorithm Design and Analysis",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399894,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521913,
                "inst_id": 1298390,
                "comp_id": 280075,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "17",
                "resultado_ects": "A",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226164,
                "ucurr_codigo": "EIC0111",
                "ucurr_sigla": "LPOO",
                "ucurr_nome": "Laboratório de Programação Orientada por Objectos",
                "ucurr_name": "Object Oriented Programming Laboratory",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399895,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521916,
                "inst_id": 1298412,
                "comp_id": 280097,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "18",
                "resultado_ects": "B",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224699,
                "ucurr_codigo": "EIC0027",
                "ucurr_sigla": "SOPE",
                "ucurr_nome": "Sistemas Operativos",
                "ucurr_name": "Operating Systems",
                "a_lectivo": 2017,
                "ano": 2,
                "ocorr_id": 399893,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11521915,
                "inst_id": 1298409,
                "comp_id": 280094,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "O",
                "avaliacao": "",
                "resultado_melhor": "16",
                "resultado_ects": "B",
                "aval_a_lectivo": 2017,
                "resultado_insc": "A",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224696,
                "ucurr_codigo": "EIC0024",
                "ucurr_sigla": "ESOF",
                "ucurr_nome": "Engenharia de Software",
                "ucurr_name": "Software Engineering",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420001,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915857,
                "inst_id": 1298388,
                "comp_id": 280073,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226118,
                "ucurr_codigo": "EIC0084",
                "ucurr_sigla": "LAIG",
                "ucurr_nome": "Laboratório de Aplicações com Interface Gráfica",
                "ucurr_name": "Graphical Applications Laboratory",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420004,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915856,
                "inst_id": 1298387,
                "comp_id": 280072,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 7.5,
                "creditos_ects": 7.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226165,
                "ucurr_codigo": "EIC0112",
                "ucurr_sigla": "LTW",
                "ucurr_nome": "Linguagens e Tecnologias Web",
                "ucurr_name": "Web Languages and Technologies",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420005,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915859,
                "inst_id": 1298414,
                "comp_id": 280099,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224698,
                "ucurr_codigo": "EIC0026",
                "ucurr_sigla": "PLOG",
                "ucurr_nome": "Programação em Lógica",
                "ucurr_name": "Logic Programming",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420002,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915855,
                "inst_id": 1298386,
                "comp_id": 280071,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 4.5,
                "creditos_ects": 4.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224704,
                "ucurr_codigo": "EIC0032",
                "ucurr_sigla": "RCOM",
                "ucurr_nome": "Redes de Computadores",
                "ucurr_name": "Computer Networks",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420003,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915858,
                "inst_id": 1298408,
                "comp_id": 280093,
                "per_id": 2,
                "per_codigo": "1S",
                "per_nome": "1º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224700,
                "ucurr_codigo": "EIC0028",
                "ucurr_sigla": "COMP",
                "ucurr_nome": "Compiladores",
                "ucurr_name": "Compilers",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420006,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915862,
                "inst_id": 1298385,
                "comp_id": 280070,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224701,
                "ucurr_codigo": "EIC0029",
                "ucurr_sigla": "IART",
                "ucurr_nome": "Inteligência Artificial",
                "ucurr_name": "Artificial Intelligence",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420007,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915861,
                "inst_id": 1298384,
                "comp_id": 280069,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 226119,
                "ucurr_codigo": "EIC0085",
                "ucurr_sigla": "LBAW",
                "ucurr_nome": "Laboratório de Bases de Dados e Aplicações Web",
                "ucurr_name": "Database and Web Applications Laboratory",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420010,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915860,
                "inst_id": 1298383,
                "comp_id": 280068,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 7.5,
                "creditos_ects": 7.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224703,
                "ucurr_codigo": "EIC0031",
                "ucurr_sigla": "PPIN",
                "ucurr_nome": "Proficiência Pessoal e Interpessoal",
                "ucurr_name": "Personal and Interpersonal Proficiency",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420008,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915864,
                "inst_id": 1298413,
                "comp_id": 280098,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 4.5,
                "creditos_ects": 4.5,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            },
            {
                "ucurr_id": 224630,
                "ucurr_codigo": "EIC0036",
                "ucurr_sigla": "SDIS",
                "ucurr_nome": "Sistemas Distribuídos",
                "ucurr_name": "Distributed Systems",
                "a_lectivo": 2018,
                "ano": 3,
                "ocorr_id": 420009,
                "ucurr_tipo": "L",
                "ucurr_duracao_tipo": "",
                "id": 11915863,
                "inst_id": 1298407,
                "comp_id": 280092,
                "per_id": 3,
                "per_codigo": "2S",
                "per_nome": "2º Semestre",
                "tipo": "N",
                "estado": "V",
                "frequencia": "I",
                "avaliacao": "",
                "resultado_melhor": "",
                "resultado_ects": "",
                "aval_a_lectivo": null,
                "resultado_insc": "N",
                "creditos_ucn": 6,
                "creditos_ects": 6,
                "n_ucurrs": 1,
                "tipo_ucurrs": "UC",
                "obr_opt": "OBR",
                "regra_eq": "",
                "devedor": "N",
                "incumpridor": "N"
            }
        ]
    }
] ''';

class PersonalInfo {
  String name;
  String courseName;
  String courseCode;
  String average;
  String year;
  List<CourseUnit> ucs;

  PersonalInfo(this.name, this.courseName, this.average, this.year, this.ucs);
  PersonalInfo.fromJSON(String json) {
    final dynamic jsonObject = jsonDecode(res);
    if (jsonObject is Map) {
      if (jsonObject.containsKey('cur_nome')) {
        this.courseName = jsonObject['curr_nome'];
      }
      if (jsonObject.containsKey('cur_sigla')) {
        this.courseCode = jsonObject['cur_sigla'];
      }
      if (jsonObject.containsKey('ano_curricular')) {
        this.year = jsonObject['ano_curricular'];
      }
      if (jsonObject.containsKey('media')) {
        this.average = jsonObject['media'];
      }
      if (jsonObject.containsKey('inscricoes')) {
        this.ucs = parseUCs(jsonObject['inscricoes']);
      }
    }
  }

  @override
    String toString() {
      return '$name\n$courseCode\n$average\n${ucs.toString()}';
    }
}

class CourseUnit {
  String year;
  String semester;
  String code;
  String name;
  String ects;
  String grade;
  bool approved;
  
  CourseUnit(this.year, this.semester, this.code, this.name, this.ects, this.grade, this.approved);

  @override
    String toString() {
      return '$year - $semester - $code - $name - $ects - $grade - $approved\n';
    }

}

List<CourseUnit> parseUCs(List<dynamic> ucs) {
  List<CourseUnit> ucs = List<CourseUnit>();
  for (var row in ucs) {
    //parse row;
    //ucs.add(CourseUnit(year, semester, code, name, ects, grade, approved));
  } 
  return ucs;
}

void main() async{
  final inst = await PersonalInfo.fromJSON(res);
  print(inst.toString());
  
}